// Auto-generate missing tag definitions based on their English IDs
// This creates a mapping for the 72 missing tags

const missingTags = [
    "adjoint-inverse", "concavity-asymptote", "confidence-interval",
    "constant-coefficient-homogeneous", "constant-coefficient-nonhomogeneous",
    "covariance-correlation", "curl-definition", "definite-integral-application",
    "definite-integral-calculation", "definite-integral-concept",
    "derivative-calculation", "derivative-concept", "derivative-geometry",
    "determinant", "differential-equation", "differential-equation-application",
    "directional-derivative", "eigenvalue-eigenvector", "equation-roots",
    "estimation-methods", "estimator-unbiased", "expectation-variance",
    "first-order-nonhomogeneous", "fourier-series", "function-continuity",
    "function-parity-periodicity", "hypothesis-testing", "improper-integral",
    "indefinite-integral", "inequality-proof", "infinitesimal-comparison",
    "inner-product", "integral-order-transform", "law-of-large-numbers",
    "limit-calculation", "limit-parameter", "line-integral-type1",
    "line-integral-type2", "linear-algebra", "linear-dependence",
    "linear-representation", "linear-solution-structure", "linear-system",
    "marginal-conditional", "matrix-diagonalization", "matrix-operation",
    "matrix-rank", "mean-value-theorem", "monotonicity-extremum",
    "multiple-integral-application", "multiple-integral-calculation",
    "multiple-integral-concept", "multivariable-extremum",
    "multivariable-geometry", "other-equations", "partial-derivative",
    "power-series-radius", "power-series-sum", "quadratic-form",
    "random-event", "random-variable", "separable-homogeneous",
    "sequence-convergence", "series-convergence", "statistics-basic",
    "surface-integral-type1", "surface-integral-type2", "taylor-formula",
    "total-differential", "two-dimensional-variable", "variable-limit-integral",
    "vector"
];

// English to Chinese mapping
const tagTranslations: Record<string, string> = {
    "adjoint-inverse": "伴随矩阵与可逆矩阵",
    "concavity-asymptote": "曲线的凹凸性、拐点及渐近线",
    "confidence-interval": "区间估计和置信区间",
    "constant-coefficient-homogeneous": "常系数齐次线性微分方程",
    "constant-coefficient-nonhomogeneous": "常系数非齐次线性微分方程",
    "covariance-correlation": "协方差与相关系数",
    "curl-definition": "旋度的定义",
    "definite-integral-application": "定积分的应用",
    "definite-integral-calculation": "定积分的计算",
    "definite-integral-concept": "定积分的概念、性质及几何意义",
    "derivative-calculation": "导数与微分的计算",
    "derivative-concept": "导数与微分的概念",
    "derivative-geometry": "导数的几何意义",
    "determinant": "行列式",
    "differential-equation": "常微分方程",
    "differential-equation-application": "微分方程的应用",
    "directional-derivative": "方向导数和梯度",
    "eigenvalue-eigenvector": "特征值与特征向量",
    "equation-roots": "方程根的存在性与个数",
    "estimation-methods": "矩估计和最大似然估计",
    "estimator-unbiased": "估计量的无偏性",
    "expectation-variance": "数学期望与方差",
    "first-order-nonhomogeneous": "一阶非齐次线性微分方程",
    "fourier-series": "傅里叶级数",
    "function-continuity": "函数的连续性",
    "function-parity-periodicity": "函数的奇偶性与周期性",
    "hypothesis-testing": "假设检验",
    "improper-integral": "反常积分的计算与敛散性",
    "indefinite-integral": "不定积分的计算",
    "inequality-proof": "不等式的证明",
    "infinitesimal-comparison": "无穷小量的比较",
    "inner-product": "向量内积与向量正交",
    "integral-order-transform": "交换积分次序与坐标系之间的转化",
    "law-of-large-numbers": "大数定律和中心极限定理",
    "limit-calculation": "函数极限的计算",
    "limit-parameter": "确定极限中的参数",
    "line-integral-type1": "第一类曲线积分",
    "line-integral-type2": "第二类曲线积分",
    "linear-algebra": "线性代数",
    "linear-dependence": "向量组的线性相关性",
    "linear-representation": "向量组之间的线性表示",
    "linear-solution-structure": "线性微分方程的解的结构",
    "linear-system": "线性方程组",
    "marginal-conditional": "边缘分布和条件分布",
    "matrix-diagonalization": "矩阵的相似与相似对角化",
    "matrix-operation": "矩阵的运算与变换",
    "matrix-rank": "矩阵的秩",
    "mean-value-theorem": "微分中值定理",
    "monotonicity-extremum": "函数的单调性、极值与最值",
    "multiple-integral-application": "重积分的应用",
    "multiple-integral-calculation": "重积分的计算",
    "multiple-integral-concept": "重积分的概念与性质",
    "multivariable-extremum": "多元函数的极值问题",
    "multivariable-geometry": "多元函数微分学的几何应用",
    "other-equations": "其他方程",
    "partial-derivative": "偏导数的概念与计算",
    "power-series-radius": "求幂级数的收敛半径、收敛区间和收敛域",
    "power-series-sum": "幂级数的和函数及幂级数展开式",
    "quadratic-form": "二次型",
    "random-event": "随机事件和概率",
    "random-variable": "随机变量及其分布",
    "separable-homogeneous": "可分离变量的微分方程与齐次方程",
    "sequence-convergence": "数列敛散性的判定",
    "series-convergence": "常数项级数敛散性的判定",
    "statistics-basic": "数理统计的基本概念",
    "surface-integral-type1": "第一类曲面积分",
    "surface-integral-type2": "第二类曲面积分",
    "taylor-formula": "泰勒公式",
    "total-differential": "全微分的概念与计算",
    "two-dimensional-variable": "二维随机变量及其分布",
    "variable-limit-integral": "变限积分",
    "vector": "向量"
};

// Generate tag objects
const generatedTags = missingTags.map(id => ({
    id,
    name: tagTranslations[id] || id,
    parentId: null  // You'll need to assign proper parent IDs manually
}));

console.log(JSON.stringify(generatedTags, null, 2));
